CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes 
LEADER_ENABLE = yes
SEND_STRING_ENABLE = yes
REPEAT_KEY_ENABLE = yes
CONSOLE_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE  = yes
TRI_LAYER_ENABLE = yes
#KEY_OVERRIDE_ENABLE = yes

SRC += my_leader_key.c